import { lstatSync, realpathSync } from "node:fs";
import path from "node:path";
import type { HumanReportSummary, ImpactMap, MissionRunResult, QAMission, QAFlowMission } from "./types.js";
import { INCOMPLETE_REPOSITORY_INVENTORY_UNKNOWN } from "./impact-mapper.js";

export const GENERATED_OUTPUT_LICENSE = {
  id: "MIT",
  url: "https://github.com/fenutech/preflight-scout/blob/main/OUTPUT-LICENSE.md",
  notice: "Template material generated by Preflight Scout in this artifact is licensed under MIT."
} as const;

export function renderMarkdownReport(input: {
  impactMap: ImpactMap;
  mission: QAMission;
  runResult?: MissionRunResult;
  runResults?: MissionRunResult[];
  runDir?: string;
  generatedAt?: string;
}): string {
  return renderHumanReport(input);
}

export function renderHumanReport(input: {
  impactMap: ImpactMap;
  mission: QAMission;
  runResult?: MissionRunResult;
  runResults?: MissionRunResult[];
  runDir?: string;
  generatedAt?: string;
}): string {
  const runResults = normalizeRunResults(input.runResult, input.runResults);
  const summary = buildHumanReportSummary({ ...input, runResults });
  const unknowns = reportUnknowns(input.impactMap, input.mission);
  const lines: string[] = [];

  lines.push("# Preflight Scout Report");
  lines.push("");
  lines.push("> RELEASE QA REPORT / LOCAL FILES / REVIEW BEFORE SHIPPING");
  lines.push("");
  lines.push(`- Generated: ${escapeUntrustedMarkdown(summary.generatedAt)}`);
  lines.push(`- Mission: ${escapeUntrustedMarkdown(input.mission.title)}`);
  lines.push(`- Risk: **${input.mission.risk.toUpperCase()}**`);
  lines.push(`- Verdict: **${formatVerdict(summary.verdict)}**`);
  lines.push("");
  lines.push("## Release result");
  lines.push("");
  lines.push(`### ${formatReleaseDecision(summary.releaseDecision.status).toUpperCase()}`);
  lines.push("");
  lines.push(escapeUntrustedMarkdown(summary.releaseDecision.reason));
  lines.push("");
  lines.push("Next steps:");
  for (const step of summary.releaseDecision.nextSteps) lines.push(`- ${escapeUntrustedMarkdown(step)}`);
  lines.push("");
  lines.push("## Mission summary");
  lines.push("");
  lines.push(escapeUntrustedMarkdown(input.mission.summary));
  lines.push("");
  lines.push("### Counts");
  lines.push("");
  lines.push(`- Affected areas: ${summary.counts.affectedAreas}`);
  lines.push(`- Manual checks: ${summary.counts.manualChecks}`);
  lines.push(`- Edge cases: ${summary.counts.edgeCases}`);
  lines.push(`- Suggested browser missions: ${summary.counts.suggestedBrowserMissions}`);
  lines.push(`- Executed browser missions: ${summary.counts.browserMissions}`);
  if (summary.counts.browserMissions > 0) {
    lines.push(`- Browser outcomes: ${summary.counts.passed} passed, ${summary.counts.failed} failed, ${summary.counts.blocked} blocked`);
  }

  lines.push("");
  lines.push("## Manual checks before production");
  lines.push("");
  for (const item of input.mission.manualChecklist) lines.push(`- [ ] ${escapeUntrustedMarkdown(item)}`);
  lines.push("");

  lines.push("## Affected areas by risk");
  lines.push("");
  for (const area of sortByRisk(input.mission.affectedAreas)) {
    lines.push(`- **${area.risk.toUpperCase()}** ${escapeUntrustedMarkdown(area.name)} (${escapeUntrustedMarkdown(area.kind)})`);
  }
  if (!input.mission.affectedAreas.length) lines.push("- No affected areas were identified.");

  lines.push("");
  lines.push("## Changed areas");
  lines.push("");
  for (const area of input.mission.affectedAreas) {
    lines.push(`### ${escapeUntrustedMarkdown(area.name)}`);
    lines.push("");
    lines.push(`Kind: ${markdownInlineCode(area.kind)}  `);
    lines.push(`Risk: **${area.risk.toUpperCase()}**`);
    lines.push("");
    for (const evidence of area.evidence) lines.push(`- ${escapeUntrustedMarkdown(evidence)}`);
    lines.push("");
  }

  if (input.impactMap.affectedRoutes.length) {
    lines.push("## Affected Routes");
    lines.push("");
    for (const route of input.impactMap.affectedRoutes) {
      lines.push(`- ${markdownInlineCode(route.path)} (${escapeUntrustedMarkdown(route.kind)}) from ${markdownInlineCode(route.file)}`);
    }
    lines.push("");
  }

  lines.push("## Edge cases to check");
  lines.push("");
  for (const item of input.mission.edgeCases) lines.push(`- ${escapeUntrustedMarkdown(item)}`);
  lines.push("");

  lines.push("## Browser results");
  lines.push("");
  if (!runResults.length) {
    if (input.mission.automationCandidates.length) {
      lines.push("No browser checks have run yet.");
      lines.push("");
      lines.push("### Suggested browser checks");
      for (const flow of input.mission.automationCandidates) {
        lines.push(`- **${escapeUntrustedMarkdown(flow.title)}** as ${markdownInlineCode(flow.role ?? "guest")} starting at ${markdownInlineCode(flow.startPath ?? "/")}`);
      }
    } else {
      lines.push("No runnable browser mission was generated. Complete the manual checklist and resolve the missing context below; no browser evidence was produced.");
    }
  } else {
    lines.push("### Results");
    lines.push("");
    for (const result of runResults) {
      const candidate = input.mission.automationCandidates.find((item) => item.id === result.missionId);
      const finalMessage = cleanMessage(result.results.at(-1)?.message);
      lines.push(`- **${escapeUntrustedMarkdown(candidate?.title ?? result.missionId)}**: ${result.status.toUpperCase()}${finalMessage ? ` - ${escapeUntrustedMarkdown(finalMessage)}` : ""}`);
    }
    lines.push("");
    for (const result of runResults) {
      const candidate = input.mission.automationCandidates.find((item) => item.id === result.missionId);
      renderMissionResult(lines, result, candidate, input.runDir);
    }
  }

  if (unknowns.length) {
    lines.push("");
    lines.push("## Needs context");
    lines.push("");
    for (const unknown of unknowns) lines.push(`- ${escapeUntrustedMarkdown(unknown)}`);
  }

  lines.push("");
  lines.push("## Machine-readable summary");
  lines.push("");
  lines.push("```json");
  lines.push(escapeJsonForMarkdown(JSON.stringify(summary, null, 2)));
  lines.push("```");
  lines.push("");
  lines.push("<!-- preflight-scout-report -->");
  lines.push(`<!-- ${GENERATED_OUTPUT_LICENSE.notice} ${GENERATED_OUTPUT_LICENSE.url} -->`);
  return lines.join("\n");
}

export function renderHumanReportHtml(input: {
  impactMap: ImpactMap;
  mission: QAMission;
  runResult?: MissionRunResult;
  runResults?: MissionRunResult[];
  runDir?: string;
  generatedAt?: string;
}): string {
  const runResults = normalizeRunResults(input.runResult, input.runResults);
  const summary = buildHumanReportSummary({ ...input, runResults });
  const unknowns = reportUnknowns(input.impactMap, input.mission);
  const releaseTone = releaseDecisionTone(summary.releaseDecision.status);
  const releaseLabel = formatReleaseDecision(summary.releaseDecision.status);
  const browserOutcome = summary.counts.browserMissions
    ? `${summary.counts.passed} passed, ${summary.counts.failed} failed, ${summary.counts.blocked} blocked`
    : "No browser results yet";
  const missionResults = runResults.length
    ? runResults.map((result) => renderMissionResultHtml(result, input.mission.automationCandidates.find((item) => item.id === result.missionId), input.runDir)).join("\n")
    : input.mission.automationCandidates.length
      ? `<section class="empty-state"><p class="empty-state__title">No browser checks have run yet.</p>
${renderList(input.mission.automationCandidates.map((flow) => `${flow.title} as ${flow.role ?? "guest"} starting at ${flow.startPath ?? "/"}`), false, "suggested-missions")}</section>`
      : `<section class="empty-state"><p class="empty-state__title">No runnable browser mission was generated.</p>
<p>Complete the manual checklist and resolve the missing context below. No browser evidence was produced.</p></section>`;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' file:; style-src 'unsafe-inline'; base-uri 'none'; connect-src 'none'; font-src 'none'; form-action 'none'; frame-src 'none'; media-src 'none'; object-src 'none'; script-src 'none'" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="generator" content="Preflight Scout" />
  <meta name="preflight-scout-output-template-license" content="${GENERATED_OUTPUT_LICENSE.id}" />
  <title>Preflight Scout Report</title>
  <style>
    :root {
      color-scheme: dark;
      --void: #02090c;
      --panel: #050e12;
      --panel-strong: #071216;
      --ink: #e8e9e5;
      --muted: #929a98;
      --faint: #68716f;
      --line: #384240;
      --line-strong: #68706a;
      --lime: #d0e94e;
      --red: #ff4b46;
      --amber: #e9c85b;
      --mono: ui-monospace, "SFMono-Regular", "Cascadia Code", "Roboto Mono", Menlo, Consolas, monospace;
    }
    * { box-sizing: border-box; }
    html { background: var(--void); }
    body {
      margin: 0;
      min-width: 320px;
      color: var(--ink);
      font: 14px/1.6 var(--mono);
      background: var(--void);
    }
    a { color: var(--lime); text-underline-offset: 3px; }
    a:hover { color: #e2f46d; }
    code {
      padding: 2px 6px;
      border: 1px solid #2d3938;
      border-radius: 2px;
      color: #d9ded8;
      background: #071115;
      font: inherit;
      overflow-wrap: anywhere;
    }
    main {
      position: relative;
      width: min(1120px, calc(100% - 48px));
      margin: 48px auto 72px;
      padding: 0 28px 28px;
      border: 1px solid var(--line-strong);
      background: #030c0f;
      box-shadow: 0 24px 72px rgba(0, 0, 0, .34), inset 0 0 48px rgba(16, 44, 48, .12);
      overflow-wrap: anywhere;
    }
    h1, h2, h3, p { overflow-wrap: anywhere; }
    h1 {
      margin: 0;
      font-size: clamp(29px, 4vw, 48px);
      line-height: 1.08;
      font-weight: 620;
      letter-spacing: .08em;
    }
    h2 {
      display: flex;
      align-items: center;
      gap: 12px;
      margin: 0 0 18px;
      color: var(--ink);
      font-size: 17px;
      line-height: 1.3;
      font-weight: 620;
      letter-spacing: .08em;
      text-transform: uppercase;
    }
    h2::before { content: attr(data-index); color: var(--lime); font-size: 11px; letter-spacing: .12em; }
    h2::after { content: ""; height: 1px; flex: 1; background: var(--line); }
    h3 { margin: 0; font-size: 17px; line-height: 1.35; font-weight: 620; }
    p { margin: 8px 0 14px; }
    ul { margin: 10px 0 18px; padding-left: 22px; }
    li { margin: 7px 0; padding-left: 3px; }
    li::marker { color: var(--lime); }
    .instrument-rail {
      display: grid;
      grid-template-columns: auto 1fr auto;
      gap: 22px;
      align-items: center;
      min-height: 48px;
      margin: 0 -12px;
      padding: 0 12px;
      border-bottom: 1px solid var(--line-strong);
      color: #9da78e;
      font-size: 10px;
      letter-spacing: .12em;
      text-transform: uppercase;
    }
    .instrument-rail > span { min-width: 0; overflow-wrap: anywhere; }
    .instrument-rail span:nth-child(2) { text-align: center; }
    .instrument-head { padding: 30px 2px 28px; border-bottom: 1px dashed var(--line-strong); }
    .kicker { margin: 0 0 15px; color: var(--lime); font-size: 11px; letter-spacing: .14em; text-transform: uppercase; }
    .risk-line { display: flex; align-items: center; gap: 12px; margin: 20px 0 0; font-size: 16px; }
    .risk-badge {
      display: inline-flex;
      align-items: center;
      min-height: 34px;
      padding: 3px 10px;
      border: 1px solid var(--amber);
      border-radius: 4px;
      color: var(--amber);
      font-size: 16px;
      letter-spacing: .08em;
    }
    .risk-badge.risk-critical, .risk-badge.risk-high { color: var(--red); border-color: #8b2d2a; }
    .risk-badge.risk-low { color: var(--lime); border-color: #6f7b38; }
    .decision {
      margin: 15px 0 12px;
      font-size: clamp(27px, 5vw, 44px);
      line-height: 1.1;
      font-weight: 700;
      letter-spacing: .055em;
      text-transform: uppercase;
    }
    .decision.hold { color: var(--red); text-shadow: 0 0 22px rgba(255, 75, 70, .1); }
    .decision.clear { color: var(--lime); text-shadow: 0 0 22px rgba(208, 233, 78, .1); }
    .decision.pending { color: var(--amber); }
    .mission-summary { max-width: 760px; color: #b3b9b5; font-size: 15px; }
    .report-section { padding: 30px 2px 8px; }
    .readiness-grid { display: grid; grid-template-columns: minmax(0, 1.25fr) minmax(260px, .75fr); gap: 30px; }
    .readiness-copy { margin-top: 0; color: #c5c9c5; }
    .flight-plan { margin: 0; padding: 18px 20px 12px 38px; border: 1px solid var(--line); background: #061014; }
    .flight-plan::before { content: "NEXT STEPS"; display: block; margin: 0 0 8px -18px; color: var(--lime); font-size: 10px; letter-spacing: .12em; }
    .summary {
      display: grid;
      grid-template-columns: repeat(6, minmax(0, 1fr));
      gap: 0;
      margin: 26px -2px 0;
      border: 1px solid var(--line);
      background: #040c0f;
    }
    .metric {
      min-width: 0;
      padding: 15px 14px;
      border-right: 1px solid var(--line);
      break-inside: avoid;
    }
    .metric:last-child { border-right: 0; }
    .metric strong { display: block; margin-top: 5px; color: var(--ink); font-size: 16px; line-height: 1.35; font-weight: 600; }
    .metric .muted { display: block; color: var(--muted); font-size: 9px; letter-spacing: .09em; text-transform: uppercase; }
    .metric[data-tone="passed"] strong { color: var(--lime); }
    .metric[data-tone="failed"] strong { color: var(--red); }
    .mission-stack { display: grid; gap: 14px; }
    .mission-card {
      position: relative;
      padding: 22px 20px 18px;
      border: 1px solid var(--line);
      border-left: 3px solid var(--amber);
      background: var(--panel);
      break-inside: avoid;
    }
    .mission-card.passed { border-left-color: var(--lime); background: #061014; }
    .mission-card.failed, .mission-card.blocked { border-left-color: var(--red); background: #100b0d; }
    .mission-card__head { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 20px; align-items: start; }
    .mission-card.passed h3, .mission-card.passed .status { color: var(--lime); }
    .mission-card.failed h3, .mission-card.failed .status,
    .mission-card.blocked h3, .mission-card.blocked .status { color: var(--red); }
    .status { align-self: center; color: var(--amber); font-size: 13px; font-weight: 700; letter-spacing: .1em; text-transform: uppercase; }
    .meta, .muted { color: var(--muted); }
    .mission-meta { margin: 7px 0 0; color: var(--muted); font-size: 11px; letter-spacing: .05em; text-transform: uppercase; }
    .mission-reason { margin-top: 18px; }
    .mission-reason > p, .evidence > p { color: #aeb4b0; font-size: 11px; letter-spacing: .09em; text-transform: uppercase; }
    .timeline { margin-top: 16px; padding-top: 14px; border-top: 1px dashed var(--line); }
    .timeline p { display: grid; grid-template-columns: auto minmax(0, 1fr); gap: 12px; margin: 10px 0; }
    .step-status { color: var(--amber); font-size: 11px; letter-spacing: .06em; }
    .step-status.passed { color: var(--lime); }
    .step-status.failed, .step-status.blocked { color: var(--red); }
    .step-status.skipped { color: var(--muted); }
    .evidence { margin-top: 16px; padding-top: 2px; }
    .evidence-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 14px; }
    .evidence-file { display: block; padding: 10px 12px; border: 1px solid var(--line); background: #040c0f; overflow-wrap: anywhere; }
    .evidence-image { margin: 0; padding: 10px; border: 1px solid var(--line); background: #040c0f; }
    .evidence-image a { display: block; margin-bottom: 9px; overflow-wrap: anywhere; }
    img { display: block; width: 100%; max-width: 100%; height: auto; border: 1px solid #303b3b; }
    .checklist { list-style: none; padding: 0; }
    .checklist li { display: grid; grid-template-columns: 18px minmax(0, 1fr); gap: 10px; align-items: start; padding: 10px 0; border-bottom: 1px dashed #283230; }
    .checklist input { width: 14px; height: 14px; margin: 5px 0 0; accent-color: var(--lime); }
    .risk-list { list-style: none; padding: 0; }
    .risk-list li { display: grid; grid-template-columns: 88px minmax(0, 1fr); gap: 14px; padding: 10px 0; border-bottom: 1px dashed #283230; }
    .risk-chip { color: var(--amber); font-weight: 700; letter-spacing: .08em; }
    .risk-chip.risk-critical, .risk-chip.risk-high { color: var(--red); }
    .risk-chip.risk-low { color: var(--lime); }
    .surface-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 12px; }
    .surface-card { padding: 18px; border: 1px solid var(--line); background: var(--panel); break-inside: avoid; }
    .surface-card h3 { font-size: 15px; }
    .surface-meta { color: var(--muted); font-size: 10px; letter-spacing: .08em; text-transform: uppercase; }
    .compact-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 28px; }
    .empty-state { padding: 20px; border: 1px dashed var(--line-strong); background: var(--panel); }
    .empty-state__title { color: var(--amber); }
    .illustrative { margin: 22px 2px 0; padding: 12px 15px; border: 1px solid #75672e; color: #d9ca81; background: rgba(103, 84, 20, .12); }
    .output-license {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      gap: 12px;
      margin-top: 32px;
      padding: 18px 2px 0;
      border-top: 1px solid var(--line-strong);
      color: var(--muted);
      font-size: 10px;
      letter-spacing: .06em;
      text-transform: uppercase;
    }
    @media (max-width: 840px) {
      main { width: min(100% - 28px, 1120px); margin-top: 20px; padding-inline: 20px; }
      .readiness-grid, .compact-grid { grid-template-columns: 1fr; }
      .summary { grid-template-columns: repeat(3, minmax(0, 1fr)); }
      .metric:nth-child(3) { border-right: 0; }
      .metric:nth-child(-n + 3) { border-bottom: 1px solid var(--line); }
    }
    @media (max-width: 560px) {
      body { font-size: 13px; }
      main { width: 100%; margin: 0; padding: 0 16px 22px; border-inline: 0; }
      .instrument-rail { grid-template-columns: auto 1fr; gap: 12px; }
      .instrument-rail span:nth-child(2) { display: none; }
      .instrument-rail span:last-child { text-align: right; }
      .instrument-head { padding-top: 24px; }
      .summary { grid-template-columns: repeat(2, minmax(0, 1fr)); }
      .metric, .metric:nth-child(3) { border-right: 1px solid var(--line); border-bottom: 1px solid var(--line); }
      .metric:nth-child(even) { border-right: 0; }
      .metric:nth-last-child(-n + 2) { border-bottom: 0; }
      .mission-card { padding: 18px 15px; }
      .mission-card__head { grid-template-columns: 1fr; gap: 7px; }
      .status { justify-self: start; }
      .timeline p { grid-template-columns: 1fr; gap: 5px; }
      .risk-list li { grid-template-columns: 72px minmax(0, 1fr); }
    }
    @page { size: A4; margin: 14mm 12mm 16mm; }
    @media print {
      html, body { background: var(--void) !important; }
      body { font-size: 11px; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      main { width: 100%; max-width: none; margin: 0; padding: 0 18px 18px; box-shadow: none; }
      .instrument-head, .metric, .mission-card, .surface-card, .flight-plan, img { break-inside: avoid; }
      .report-section { padding-top: 22px; }
      .summary { grid-template-columns: repeat(3, minmax(0, 1fr)); }
      .metric:nth-child(3) { border-right: 0; }
      .metric:nth-child(-n + 3) { border-bottom: 1px solid var(--line); }
      .readiness-grid, .compact-grid { grid-template-columns: 1fr; gap: 14px; }
      img { max-height: 36vh; object-fit: contain; }
      a { color: var(--lime); text-decoration: none; }
    }
  </style>
</head>
<body>
<main class="report-shell">
  <div class="instrument-rail" aria-label="Report metadata">
    <span>PS-01 / local run</span>
    <span>Mission ${escapeHtml(input.mission.id)}</span>
    <span>${escapeHtml(summary.generatedAt)}</span>
  </div>
  <header class="instrument-head">
    <p class="kicker">Preflight Scout / release QA report</p>
    <h1>PRE-FLIGHT REPORT</h1>
    <p class="risk-line">Risk <span class="risk-badge ${riskClass(input.mission.risk)}">${escapeHtml(input.mission.risk.toUpperCase())}</span></p>
    <p class="decision ${releaseTone}">${escapeHtml(releaseLabel)}</p>
    <p class="mission-summary">${escapeHtml(input.mission.summary)}</p>
  </header>

  <section class="report-section" aria-labelledby="release-readiness">
    <h2 id="release-readiness" data-index="01">Release result</h2>
    <div class="readiness-grid">
      <div>
        <p class="readiness-copy"><strong>${escapeHtml(formatVerdict(summary.verdict))}.</strong> ${escapeHtml(summary.releaseDecision.reason)}</p>
      </div>
      ${renderList(summary.releaseDecision.nextSteps, false, "flight-plan")}
    </div>
  </section>
  <section class="summary" aria-label="Report summary">
    ${metric("Affected areas", summary.counts.affectedAreas)}
    ${metric("Manual checks", summary.counts.manualChecks)}
    ${metric("Edge cases", summary.counts.edgeCases)}
    ${metric("Suggested browser checks", summary.counts.suggestedBrowserMissions)}
    ${metric("Executed browser checks", summary.counts.browserMissions)}
    ${metric("Browser outcomes", browserOutcome, summary.counts.failed || summary.counts.blocked ? "failed" : summary.counts.browserMissions ? "passed" : undefined)}
  </section>

  <section class="report-section" aria-labelledby="browser-flight-checks">
    <h2 id="browser-flight-checks" data-index="02">Browser results</h2>
    <div class="mission-stack">${missionResults}</div>
  </section>

  <section class="report-section" aria-labelledby="pre-ship-checklist">
    <h2 id="pre-ship-checklist" data-index="03">Manual checks before production</h2>
    ${renderChecklist(input.mission.manualChecklist)}
  </section>

  <section class="report-section" aria-labelledby="risk-radar">
    <h2 id="risk-radar" data-index="04">Affected areas by risk</h2>
    ${renderRiskList(input.mission.affectedAreas)}
  </section>

  <section class="report-section" aria-labelledby="changed-surface">
    <h2 id="changed-surface" data-index="05">Changed areas</h2>
    ${renderAffectedAreas(input.mission.affectedAreas)}
  </section>

  <div class="compact-grid">
    ${input.impactMap.affectedRoutes.length ? `<section class="report-section" aria-labelledby="affected-routes"><h2 id="affected-routes" data-index="06">Affected Routes</h2>${renderList(input.impactMap.affectedRoutes.map((route) => `<code>${escapeHtml(route.path)}</code> (${escapeHtml(route.kind)}) from <code>${escapeHtml(route.file)}</code>`), true)}</section>` : ""}
    <section class="report-section" aria-labelledby="edge-cases"><h2 id="edge-cases" data-index="07">Edge cases to check</h2>${renderList(input.mission.edgeCases)}</section>
  </div>

  ${unknowns.length ? `<section class="report-section" aria-labelledby="human-context"><h2 id="human-context" data-index="08">Needs context</h2>${renderList(unknowns)}</section>` : ""}
  <footer class="output-license"><span>Local files / review before shipping</span><span>${GENERATED_OUTPUT_LICENSE.notice} <a href="${GENERATED_OUTPUT_LICENSE.url}">Output license</a>.</span></footer>
</main>
</body>
</html>
`;
}

export function buildHumanReportSummary(input: {
  impactMap: ImpactMap;
  mission: QAMission;
  runResult?: MissionRunResult;
  runResults?: MissionRunResult[];
  generatedAt?: string;
}): HumanReportSummary {
  const runResults = normalizeRunResults(input.runResult, input.runResults);
  const passed = runResults.filter((result) => result.status === "passed").length;
  const failed = runResults.filter((result) => result.status === "failed").length;
  const blocked = runResults.filter((result) => result.status === "blocked").length;
  const incompleteRepositoryInventory = input.impactMap.unknowns.includes(INCOMPLETE_REPOSITORY_INVENTORY_UNKNOWN);
  return {
    generatedAt: input.generatedAt ?? new Date().toISOString(),
    title: input.mission.title,
    risk: input.mission.risk,
    verdict: incompleteRepositoryInventory ? "needs_attention" : runResults.length === 0 ? "no_browser_evidence" : failed > 0 || blocked > 0 ? "needs_attention" : "ready_for_human_review",
    releaseDecision: releaseDecision(input.impactMap, input.mission, runResults, { failed, blocked }),
    counts: {
      affectedAreas: input.mission.affectedAreas.length,
      manualChecks: input.mission.manualChecklist.length,
      edgeCases: input.mission.edgeCases.length,
      suggestedBrowserMissions: input.mission.automationCandidates.length,
      browserMissions: runResults.length,
      passed,
      failed,
      blocked
    },
    browserMissions: runResults.map((result) => {
      const candidate = input.mission.automationCandidates.find((item) => item.id === result.missionId);
      return {
        id: result.missionId,
        title: candidate?.title,
        risk: candidate?.risk,
        status: result.status,
        finalMessage: cleanMessage(result.results.at(-1)?.message),
        artifacts: result.artifacts,
        evidence: result.evidence
      };
    })
  };
}

function renderMissionResult(lines: string[], result: MissionRunResult, candidate: QAFlowMission | undefined, runDir: string | undefined): void {
  lines.push(`### ${escapeUntrustedMarkdown(candidate?.title ?? result.missionId)}`);
  lines.push("");
  lines.push(`Status: **${result.status.toUpperCase()}**  `);
  if (candidate?.risk) lines.push(`Risk: **${candidate.risk.toUpperCase()}**  `);
  if (candidate?.role) lines.push(`Role: ${markdownInlineCode(candidate.role)}  `);
  if (candidate?.startPath) lines.push(`Start: ${markdownInlineCode(candidate.startPath)}`);
  lines.push("");

  if (candidate?.reason.length) {
    lines.push("Why this mattered:");
    for (const reason of candidate.reason) lines.push(`- ${escapeUntrustedMarkdown(reason)}`);
    lines.push("");
  }

  lines.push("Result timeline:");
  for (const step of result.results) {
    lines.push(`- ${step.status.toUpperCase()} ${markdownInlineCode(step.stepId)}: ${escapeUntrustedMarkdown(cleanMessage(step.message) ?? "")}`);
  }
  lines.push("");

  const evidence = selectRenderedEvidence(result, runDir);
  if (evidence.length) {
    lines.push("Evidence:");
    for (const item of evidence) {
      const label = escapeUntrustedMarkdown(item.label);
      lines.push(`- [${label}](${item.href})`);
      if (item.image) lines.push(`  ![${label}](${item.href})`);
    }
    lines.push("");
  }
}

function renderMissionResultHtml(result: MissionRunResult, candidate: QAFlowMission | undefined, runDir: string | undefined): string {
  const evidence = selectRenderedEvidence(result, runDir);
  return `<section class="mission-card ${result.status}">
  <header class="mission-card__head">
    <div>
      <h3>${escapeHtml(candidate?.title ?? result.missionId)}</h3>
      <p class="mission-meta">${candidate?.risk ? `Risk ${escapeHtml(candidate.risk.toUpperCase())} · ` : ""}${candidate?.role ? `Role ${escapeHtml(candidate.role)} · ` : ""}${candidate?.startPath ? `Start ${escapeHtml(candidate.startPath)}` : ""}</p>
    </div>
    <span class="status ${result.status}">${escapeHtml(result.status)}</span>
  </header>
  ${candidate?.reason.length ? `<div class="mission-reason"><p>Why this mattered</p>${renderList(candidate.reason)}</div>` : ""}
  <div class="timeline">
    ${result.results.map((step) => `<p><strong class="step-status ${step.status}">${escapeHtml(step.status.toUpperCase())}</strong><span><code>${escapeHtml(step.stepId)}</code> ${escapeHtml(cleanMessage(step.message) ?? "")}</span></p>`).join("\n")}
  </div>
${evidence.length ? `  <div class="evidence"><p>Evidence</p><div class="evidence-grid">${evidence.map((item) => renderEvidenceHtml(item)).join("\n")}</div></div>\n` : ""}
</section>`;
}

function renderEvidenceHtml(evidence: RenderedEvidence): string {
  const label = escapeHtml(evidence.label);
  const href = escapeAttribute(evidence.href);
  return evidence.image
    ? `<figure class="evidence-image"><a href="${href}">${label}</a><img src="${href}" alt="${label}" /></figure>`
    : `<a class="evidence-file" href="${href}">${label}</a>`;
}

function metric(label: string, value: string | number, tone?: "passed" | "failed"): string {
  return `<div class="metric"${tone ? ` data-tone="${tone}"` : ""}><span class="muted">${escapeHtml(label)}</span><strong>${escapeHtml(String(value))}</strong></div>`;
}

function renderChecklist(items: string[]): string {
  if (!items.length) return "<p class=\"muted\">None.</p>";
  return `<ul class="checklist">${items.map((item) => `<li><input type="checkbox" disabled aria-label="Not yet checked" /><span>${escapeHtml(item)}</span></li>`).join("")}</ul>`;
}

function renderList(items: string[], trustedHtml = false, className?: string): string {
  if (!items.length) return "<p class=\"muted\">None.</p>";
  return `<ul${className ? ` class="${className}"` : ""}>${items.map((item) => `<li>${trustedHtml ? item : escapeHtml(item)}</li>`).join("")}</ul>`;
}

function renderRiskList(areas: QAMission["affectedAreas"]): string {
  if (!areas.length) return "<p class=\"muted\">No affected areas were identified.</p>";
  return `<ul class="risk-list">${sortByRisk(areas).map((area) => `<li><span class="risk-chip ${riskClass(area.risk)}">${escapeHtml(area.risk.toUpperCase())}</span><span>${escapeHtml(area.name)} <span class="muted">(${escapeHtml(area.kind)})</span></span></li>`).join("")}</ul>`;
}

function renderAffectedAreas(areas: QAMission["affectedAreas"]): string {
  if (!areas.length) return "<p class=\"muted\">No changed areas were identified.</p>";
  return `<div class="surface-grid">${areas.map((area) => `<article class="surface-card"><h3>${escapeHtml(area.name)}</h3><p class="surface-meta">Kind ${escapeHtml(area.kind)} · Risk ${escapeHtml(area.risk.toUpperCase())}</p>${renderList(area.evidence)}</article>`).join("\n")}</div>`;
}

function releaseDecision(
  impactMap: ImpactMap,
  mission: QAMission,
  runResults: MissionRunResult[],
  counts: { failed: number; blocked: number }
): HumanReportSummary["releaseDecision"] {
  if (impactMap.unknowns.includes(INCOMPLETE_REPOSITORY_INVENTORY_UNKNOWN)) {
    return {
      status: "do_not_ship_yet",
      reason: "Repository inventory was incomplete, so the impact analysis is not exhaustive.",
      nextSteps: [
        "Reduce the eligible repository inventory or raise the reviewed file limit before relying on this analysis.",
        "Rerun Preflight Scout and review a report with complete repository coverage."
      ]
    };
  }
  if (!runResults.length) {
    if (!mission.automationCandidates.length) {
      return {
        status: "needs_browser_evidence",
        reason: "The analysis produced manual checks only because no safe final-state browser assertion was available.",
        nextSteps: [
          "Complete the manual checklist and record the result before production.",
          "Add deterministic final-state selectors or expected text before regenerating browser missions.",
          ...mission.unknowns.map((unknown) => `Resolve missing context: ${unknown}`)
        ]
      };
    }
    return {
      status: "needs_browser_evidence",
      reason: "The checklist is ready, but no browser checks have run.",
      nextSteps: [
        "Run the suggested browser missions against a local, preview, or staging URL.",
        "Complete the must-test checklist before production.",
        ...mission.unknowns.map((unknown) => `Resolve missing context: ${unknown}`)
      ]
    };
  }
  if (counts.failed > 0 || counts.blocked > 0) {
    return {
      status: "do_not_ship_yet",
      reason: `${counts.failed} browser check${counts.failed === 1 ? "" : "s"} failed; ${counts.blocked} ${counts.blocked === 1 ? "was" : "were"} blocked.`,
      nextSteps: [
        "Review the failed or blocked mission evidence.",
        "Fix the issue or provide the missing credentials, permissions, approval, or safe test data.",
        "Rerun Preflight Scout before production."
      ]
    };
  }
  return {
    status: "ready_for_human_review",
    reason: "Every browser check that ran passed. Review the manual checklist and any edge cases that were not run.",
    nextSteps: [
      "Review the browser evidence screenshots and trace.",
      "Complete any manual checks that were not covered by browser missions.",
      "Keep this report with the release notes."
    ]
  };
}

function reportUnknowns(impactMap: ImpactMap, mission: QAMission): string[] {
  return [...new Set([...impactMap.unknowns, ...mission.unknowns])];
}

function formatReleaseDecision(status: HumanReportSummary["releaseDecision"]["status"]): string {
  if (status === "ready_for_human_review") return "Ready for human review";
  if (status === "needs_browser_evidence") return "Needs browser evidence";
  return "Do not ship yet";
}

function releaseDecisionTone(status: HumanReportSummary["releaseDecision"]["status"]): "clear" | "pending" | "hold" {
  if (status === "ready_for_human_review") return "clear";
  if (status === "needs_browser_evidence") return "pending";
  return "hold";
}

function riskClass(risk: string): string {
  if (risk === "critical") return "risk-critical";
  if (risk === "high") return "risk-high";
  if (risk === "low") return "risk-low";
  return "risk-medium";
}

function sortByRisk<T extends { risk: string }>(items: T[]): T[] {
  const weight: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
  return [...items].sort((a, b) => (weight[a.risk] ?? 99) - (weight[b.risk] ?? 99));
}

function selectEvidence(result: MissionRunResult): string[] {
  const explicit = result.results
    .map((step) => step.screenshotPath)
    .filter((item): item is string => Boolean(item));
  const structured = result.evidence
    ? [
        result.evidence.tracePath,
        result.evidence.consolePath,
        result.evidence.networkPath,
        result.evidence.finalObservationPath
      ].filter((item): item is string => Boolean(item))
    : [];
  return [...new Set([...explicit, ...structured])];
}

interface RenderedEvidence {
  href: string;
  image: boolean;
  label: string;
}

function selectRenderedEvidence(result: MissionRunResult, runDir: string | undefined): RenderedEvidence[] {
  if (!runDir) return [];

  let lexicalRoot: string;
  let canonicalRoot: string;
  try {
    lexicalRoot = path.resolve(runDir);
    const rootStat = lstatSync(lexicalRoot);
    if (!rootStat.isDirectory() || rootStat.isSymbolicLink()) return [];
    canonicalRoot = realpathSync(lexicalRoot);
  } catch {
    return [];
  }

  const rendered: RenderedEvidence[] = [];
  const seen = new Set<string>();
  for (const source of selectEvidence(result)) {
    if (hasUriScheme(source)) continue;
    const candidate = path.isAbsolute(source) ? path.resolve(source) : path.resolve(lexicalRoot, source);
    if (!isPathWithin(lexicalRoot, candidate) || containsSymlink(lexicalRoot, candidate)) continue;

    try {
      const candidateStat = lstatSync(candidate);
      if (!candidateStat.isFile() || candidateStat.isSymbolicLink() || candidateStat.nlink !== 1) continue;
      const canonicalCandidate = realpathSync(candidate);
      if (!isPathWithin(canonicalRoot, canonicalCandidate) || seen.has(canonicalCandidate)) continue;
      const relative = path.relative(canonicalRoot, canonicalCandidate);
      if (!relative || path.isAbsolute(relative) || relative.split(path.sep).some((segment) => segment === ".." || segment === ".")) continue;
      const href = relative.split(path.sep).map((segment) => encodeURIComponent(segment)).join("/");
      const label = path.basename(canonicalCandidate);
      rendered.push({ href, image: isImage(label), label });
      seen.add(canonicalCandidate);
    } catch {
      // Evidence may be removed between execution and report rendering. Omit it.
    }
  }
  return rendered;
}

function normalizeRunResults(runResult?: MissionRunResult, runResults?: MissionRunResult[]): MissionRunResult[] {
  if (runResults?.length) return runResults;
  return runResult ? [runResult] : [];
}

function hasUriScheme(value: string): boolean {
  if (process.platform === "win32" && /^[A-Za-z]:[\\/]/.test(value)) return false;
  return /^[A-Za-z][A-Za-z0-9+.-]*:/.test(value);
}

function isPathWithin(root: string, candidate: string): boolean {
  const relative = path.relative(root, candidate);
  return relative === "" || (!path.isAbsolute(relative) && relative !== ".." && !relative.startsWith(`..${path.sep}`));
}

function containsSymlink(root: string, candidate: string): boolean {
  const relative = path.relative(root, candidate);
  if (!relative || path.isAbsolute(relative) || relative === ".." || relative.startsWith(`..${path.sep}`)) return true;
  let current = root;
  for (const segment of relative.split(path.sep)) {
    current = path.join(current, segment);
    try {
      if (lstatSync(current).isSymbolicLink()) return true;
    } catch {
      return true;
    }
  }
  return false;
}

function isImage(filePath: string): boolean {
  return /\.(png|jpe?g|webp)$/i.test(filePath);
}

function formatVerdict(verdict: HumanReportSummary["verdict"]): string {
  if (verdict === "ready_for_human_review") return "Ready for human review";
  if (verdict === "needs_attention") return "Needs attention before production";
  return "No browser evidence yet";
}

function escapeUntrustedMarkdown(value: string): string {
  let clean = sanitizeUntrustedText(value);
  for (const character of ["\\", "`", "*", "_", "[", "]", "(", ")", "#", "~", "|"]) {
    clean = clean.replaceAll(character, `\\${character}`);
  }
  return clean;
}

function markdownInlineCode(value: string): string {
  const clean = sanitizeUntrustedText(value);
  const longestRun = Math.max(0, ...[...clean.matchAll(/`+/g)].map((match) => match[0].length));
  const fence = "`".repeat(longestRun + 1);
  return `${fence}${clean}${fence}`;
}

function sanitizeUntrustedText(value: string): string {
  return value
    .replace(/\s+/g, " ")
    .trim()
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/@(?=[A-Za-z0-9_-])/g, "@\u200b")
    .replace(/\b([A-Za-z][A-Za-z0-9+.-]*):/g, "$1\u200b:");
}

function escapeJsonForMarkdown(value: string): string {
  return value.replace(/[<>&@]/g, (character) => {
    if (character === "<") return "\\u003c";
    if (character === ">") return "\\u003e";
    if (character === "@") return "\\u0040";
    return "\\u0026";
  });
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeAttribute(value: string): string {
  return escapeHtml(value).replace(/"/g, "&quot;");
}

function cleanMessage(value: string | undefined): string | undefined {
  if (!value) return undefined;
  return value
    .replace(/\u001b\[[0-9;]*m/g, "")
    .replace(/\r/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}
