import { link, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import type { MissionRunResult } from "@preflight-scout/core";
import { listArtifactFiles, reportArtifactPaths } from "./artifacts.js";

describe("listArtifactFiles", () => {
  let temporaryRoot: string;
  let artifacts: string;

  beforeEach(async () => {
    temporaryRoot = await mkdtemp(path.join(tmpdir(), "preflight-scout-action-artifacts-"));
    artifacts = path.join(temporaryRoot, "artifacts");
    await mkdir(path.join(artifacts, "nested"), { recursive: true });
  });

  afterEach(async () => {
    await rm(temporaryRoot, { recursive: true, force: true });
  });

  it("returns only regular files beneath the artifact root", async () => {
    const report = path.join(artifacts, "report.md");
    const screenshot = path.join(artifacts, "nested", "screen.png");
    await writeFile(report, "safe report\n");
    await writeFile(screenshot, "safe screenshot\n");

    await expect(listArtifactFiles(artifacts, [report, screenshot])).resolves.toEqual([screenshot, report].sort());
  });

  it.skipIf(process.platform === "win32")("rejects file and directory symlinks without reading their external targets", async () => {
    const externalDirectory = path.join(temporaryRoot, "runner-secrets");
    const externalSecret = path.join(externalDirectory, "token.txt");
    await mkdir(externalDirectory);
    await writeFile(externalSecret, "do-not-upload\n");
    await symlink(externalSecret, path.join(artifacts, "leaked-token.txt"));

    await expect(listArtifactFiles(artifacts, [path.join(artifacts, "leaked-token.txt")])).rejects.toThrow("symbolic link");
    expect(await readFile(externalSecret, "utf8")).toBe("do-not-upload\n");

    await rm(path.join(artifacts, "leaked-token.txt"));
    await symlink(externalDirectory, path.join(artifacts, "external-directory"));
    await expect(listArtifactFiles(artifacts, [path.join(artifacts, "external-directory", "token.txt")])).rejects.toThrow("symbolic link");
  });

  it.skipIf(process.platform === "win32")("rejects hard links that alias files outside the artifact root", async () => {
    const externalSecret = path.join(temporaryRoot, "runner-token.txt");
    await writeFile(externalSecret, "do-not-upload\n");
    await link(externalSecret, path.join(artifacts, "hard-linked-token.txt"));

    await expect(listArtifactFiles(artifacts, [path.join(artifacts, "hard-linked-token.txt")])).rejects.toThrow("hard-linked");
  });

  it("excludes stale regular files that were not generated by the current run", async () => {
    const report = path.join(artifacts, "report.md");
    const staleSecret = path.join(artifacts, "stale-auth-state.json");
    await writeFile(report, "safe report\n");
    await writeFile(staleSecret, '{"cookies":[{"value":"do-not-upload"}]}\n');

    await expect(listArtifactFiles(artifacts, [report])).resolves.toEqual([report]);
  });

  it("builds an explicit manifest from reports and current mission evidence", () => {
    const screenshot = path.join(artifacts, "nested", "screen.png");
    const trace = path.join(artifacts, "nested", "trace.zip");
    const result: MissionRunResult = {
      missionId: "checkout",
      status: "passed",
      results: [{ stepId: "verify", status: "passed", screenshotPath: screenshot }],
      artifacts: [screenshot, trace],
      evidence: { tracePath: trace }
    };

    const manifest = reportArtifactPaths(artifacts, [result]);

    expect(manifest).toContain(path.join(artifacts, "report.md"));
    expect(manifest).toContain(path.join(artifacts, "run-results.json"));
    expect(manifest).toContain(screenshot);
    expect(manifest).toContain(trace);
    expect(manifest.filter((item) => item === screenshot)).toHaveLength(1);
  });
});
